version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=453169210778.dkr.ecr.us-east-1.amazonaws.com/test1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 453169210778.dkr.ecr.us-east-1.amazonaws.com/test1
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"exam-task","imageUri":"453169210778.dkr.ecr.us-east-1.amazonaws.com/test"}]' > images.json

artifacts:
  files: images.json
